// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetPulse.Infrastructure.Persistence;

#nullable disable

namespace PetPulse.Infrastructure.Migrations
{
    [DbContext(typeof(PetPulseContext))]
    partial class PetPulseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetPulse.Domain.entites.AlertaInteligente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_GERACAO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<int>("OrigemAlerta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORIGEM_ALERTA");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("Recomendacao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("RECOMENDACAO");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<int>("TipoAlerta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO_ALERTA");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("PP_AlertasInteligentes", (string)null);
                });

            modelBuilder.Entity("PetPulse.Domain.entites.DispositivoIot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<DateTime?>("DataUltimaLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ULTIMA_LEITURA");

                    b.Property<string>("DataVinculacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_VINCULACAO");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FREQUENCIA_CARDIACA");

                    b.Property<int?>("IntervaloColetaMinutos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("INTERVALO_COLETA_MINUTOS");

                    b.Property<decimal?>("NivelAtividade")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("NIVEL_ATIVIDADE");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<decimal?>("Pressao")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("PRESSAO");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.ToTable("PP_DispositivoIots", (string)null);
                });

            modelBuilder.Entity("PetPulse.Domain.entites.HistoricoClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_HISTORICO");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_REGISTRO");

                    b.Property<string>("DataRetorno")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_RETORNO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("ProfissionalClinica")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("PROFISSIONAL_CLINICA");

                    b.Property<int>("TipoRegistro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO_REGISTRO");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("PP_HistoricoClinicos", (string)null);
                });

            modelBuilder.Entity("PetPulse.Domain.entites.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<int>("Castrado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CASTRADO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("PESO");

                    b.Property<int>("Porte")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PORTE");

                    b.Property<string>("Raca")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RACA");

                    b.Property<int>("Sexo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SEXO");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PP_Pets", (string)null);
                });

            modelBuilder.Entity("PetPulse.Domain.entites.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PP_Usuarios", (string)null);
                });

            modelBuilder.Entity("PetPulse.Domain.entites.AlertaInteligente", b =>
                {
                    b.HasOne("PetPulse.Domain.entites.Pet", "Pet")
                        .WithMany("AlertasInteligentes")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetPulse.Domain.entites.DispositivoIot", b =>
                {
                    b.HasOne("PetPulse.Domain.entites.Pet", "Pet")
                        .WithOne("DispositivoIot")
                        .HasForeignKey("PetPulse.Domain.entites.DispositivoIot", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetPulse.Domain.entites.HistoricoClinico", b =>
                {
                    b.HasOne("PetPulse.Domain.entites.Pet", "Pet")
                        .WithMany("HistoricosClinicos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetPulse.Domain.entites.Pet", b =>
                {
                    b.HasOne("PetPulse.Domain.entites.Usuario", "Usuario")
                        .WithMany("Pets")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetPulse.Domain.entites.Pet", b =>
                {
                    b.Navigation("AlertasInteligentes");

                    b.Navigation("DispositivoIot");

                    b.Navigation("HistoricosClinicos");
                });

            modelBuilder.Entity("PetPulse.Domain.entites.Usuario", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
